import { Crimson_Pro, Lato } from "next/font/google";
import "./globals.css";

export const crimson = Crimson_Pro({
  subsets: ["latin"],
  variable: "--font-crimson",
});
export const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-lato",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} bg-rose text-myBlue font-lato h-screen antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
